name: 'Constellos Review Actions'
description: 'AI-powered code review using Claude - modular review actions for PR quality'
author: 'Constellos'

branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  review_type:
    description: 'Type of review (requirements, code-quality)'
    required: false
    default: 'requirements'
  claude_code_oauth_token:
    description: 'Claude Code OAuth token'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  branch:
    description: 'Branch name (for requirements review issue extraction)'
    required: false
  github_token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}

outputs:
  passed:
    description: 'Whether review passed (all checks passed)'
    value: ${{ steps.review.outputs.passed }}
  result:
    description: 'JSON review result with checks array'
    value: ${{ steps.review.outputs.result }}
  checks_passed:
    description: 'Number of checks that passed'
    value: ${{ steps.review.outputs.checks_passed }}
  checks_failed:
    description: 'Number of checks that failed'
    value: ${{ steps.review.outputs.checks_failed }}
  checks_skipped:
    description: 'Number of checks that were skipped'
    value: ${{ steps.review.outputs.checks_skipped }}

runs:
  using: 'composite'
  steps:
    - name: Run requirements reviewer
      id: requirements-review
      if: inputs.review_type == 'requirements'
      uses: ./.github/actions/requirements-reviewer
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        pr_number: ${{ inputs.pr_number }}
        branch: ${{ inputs.branch }}
        github_token: ${{ inputs.github_token }}

    - name: Run code-quality reviewer
      id: code-quality-review
      if: inputs.review_type == 'code-quality'
      uses: ./.github/actions/code-quality-reviewer
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        pr_number: ${{ inputs.pr_number }}
        github_token: ${{ inputs.github_token }}

    - name: Set outputs
      id: review
      shell: bash
      run: |
        if [ "${{ inputs.review_type }}" = "requirements" ]; then
          echo "passed=${{ steps.requirements-review.outputs.passed }}" >> $GITHUB_OUTPUT
          echo "result=${{ steps.requirements-review.outputs.result }}" >> $GITHUB_OUTPUT
          echo "checks_passed=${{ steps.requirements-review.outputs.checks_passed }}" >> $GITHUB_OUTPUT
          echo "checks_failed=${{ steps.requirements-review.outputs.checks_failed }}" >> $GITHUB_OUTPUT
          echo "checks_skipped=${{ steps.requirements-review.outputs.checks_skipped }}" >> $GITHUB_OUTPUT
        else
          echo "passed=${{ steps.code-quality-review.outputs.passed }}" >> $GITHUB_OUTPUT
          echo "result=${{ steps.code-quality-review.outputs.result }}" >> $GITHUB_OUTPUT
          echo "checks_passed=${{ steps.code-quality-review.outputs.checks_passed }}" >> $GITHUB_OUTPUT
          echo "checks_failed=${{ steps.code-quality-review.outputs.checks_failed }}" >> $GITHUB_OUTPUT
          echo "checks_skipped=${{ steps.code-quality-review.outputs.checks_skipped }}" >> $GITHUB_OUTPUT
        fi
