name: Visual Reviewer
description: AI visual design & accessibility review with screenshot analysis

branding:
  icon: 'eye'
  color: 'blue'

inputs:
  claude_code_oauth_token:
    description: 'Claude Code OAuth token'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true
  screenshots_dir:
    description: 'Directory containing screenshots'
    required: false
    default: '.claude/screenshots'
  approvals_file:
    description: 'Path to visual approvals JSON file'
    required: false
    default: '.claude-review/visual-approvals.json'
  model:
    description: 'Claude model to use for visual analysis'
    required: false
    default: 'claude-sonnet-4-5-20250929'

outputs:
  passed:
    description: 'Whether the review passed (all checks passed)'
    value: ${{ steps.extract.outputs.passed }}
  result:
    description: 'JSON result from the review'
    value: ${{ steps.extract.outputs.result }}
  checks_passed:
    description: 'Number of checks that passed'
    value: ${{ steps.extract.outputs.checks_passed }}
  checks_failed:
    description: 'Number of checks that failed'
    value: ${{ steps.extract.outputs.checks_failed }}
  checks_skipped:
    description: 'Number of checks that were skipped'
    value: ${{ steps.extract.outputs.checks_skipped }}
  regression_detected:
    description: 'Whether visual regression was detected'
    value: ${{ steps.regression.outputs.detected }}
  changed_screenshots:
    description: 'List of screenshots that changed'
    value: ${{ steps.regression.outputs.changed }}

runs:
  using: composite
  steps:
    - name: Check for screenshots
      id: check
      shell: bash
      run: |
        mkdir -p ${{ inputs.screenshots_dir }}
        mkdir -p $(dirname ${{ inputs.approvals_file }})

        COUNT=$(ls -1 ${{ inputs.screenshots_dir }}/*.png 2>/dev/null | wc -l || echo "0")
        echo "count=$COUNT" >> $GITHUB_OUTPUT

    - name: Check for regressions
      id: regression
      shell: bash
      run: |
        APPROVAL_FILE="${{ inputs.approvals_file }}"
        SCREENSHOTS_DIR="${{ inputs.screenshots_dir }}"
        CHANGED=""
        NEW=""
        DETECTED="false"

        if [ -f "$APPROVAL_FILE" ] && [ "${{ steps.check.outputs.count }}" != "0" ]; then
          for screenshot in "$SCREENSHOTS_DIR"/*.png; do
            [ -f "$screenshot" ] || continue
            name=$(basename "$screenshot")
            current_hash=$(sha256sum "$screenshot" | cut -d' ' -f1)

            # Check if this screenshot was previously approved
            approved_hash=$(jq -r ".approvals[] | select(.screenshot == \"$name\") | .hash // \"\"" "$APPROVAL_FILE" 2>/dev/null || echo "")

            if [ -z "$approved_hash" ]; then
              NEW="$NEW $name"
            elif [ "$current_hash" != "$approved_hash" ]; then
              CHANGED="$CHANGED $name"
              DETECTED="true"
            fi
          done
        fi

        echo "detected=$DETECTED" >> $GITHUB_OUTPUT
        echo "changed=$CHANGED" >> $GITHUB_OUTPUT
        echo "new=$NEW" >> $GITHUB_OUTPUT

        # Determine message type
        if [ -n "$CHANGED" ]; then
          echo "message_type=regression" >> $GITHUB_OUTPUT
        elif [ -n "$NEW" ]; then
          echo "message_type=new" >> $GITHUB_OUTPUT
        else
          echo "message_type=unchanged" >> $GITHUB_OUTPUT
        fi

    - name: Load agent prompt
      id: agent
      shell: bash
      run: |
        MSG_TYPE="${{ steps.regression.outputs.message_type }}"
        CHANGED="${{ steps.regression.outputs.changed }}"
        NEW="${{ steps.regression.outputs.new }}"

        case "$MSG_TYPE" in
          "regression")
            CONTEXT="VISUAL REGRESSION - Changed: $CHANGED"
            ;;
          "new")
            CONTEXT="NEW SCREENSHOTS - New: $NEW"
            ;;
          *)
            CONTEXT="All screenshots match approved versions"
            ;;
        esac

        if [ -f ".claude/agents/reviewers/visual.md" ]; then
          BASE_PROMPT=$(cat .claude/agents/reviewers/visual.md)
        else
          BASE_PROMPT="# Visual Review - Screenshots in ${{ inputs.screenshots_dir }}/"
        fi

        FULL_PROMPT="$BASE_PROMPT
        $CONTEXT
        Evaluate: Design, Accessibility, Responsiveness
        Output json {passed: bool, summary: ...}"

        echo "prompt<<ENDOFPROMPT" >> $GITHUB_OUTPUT
        echo "$FULL_PROMPT" >> $GITHUB_OUTPUT
        echo "ENDOFPROMPT" >> $GITHUB_OUTPUT

    - name: Run review
      if: steps.check.outputs.count != '0'
      id: review
      uses: anthropics/claude-code-base-action@main
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        allowed_tools: "View,GlobTool,Bash(ls:*)"
        max_turns: 20
        model: ${{ inputs.model }}
        prompt: ${{ steps.agent.outputs.prompt }}

    - name: Extract result
      id: extract
      shell: bash
      run: |
        # Initialize defaults
        CHECKS_PASSED=0
        CHECKS_FAILED=0
        CHECKS_SKIPPED=0
        PASSED="false"
        RESULT='{"checks":[],"message":"Review failed to complete"}'

        # Handle case when no screenshots exist
        if [ "${{ steps.check.outputs.count }}" = "0" ]; then
          PASSED="true"
          CHECKS_SKIPPED=5
          RESULT='{"checks":[{"name":"Design Consistency","status":"skipped","result":"No screenshots to review","reasoning":"No screenshots found","files":[]},{"name":"Accessibility","status":"skipped","result":"No screenshots to review","reasoning":"No screenshots found","files":[]},{"name":"Responsiveness","status":"skipped","result":"No screenshots to review","reasoning":"No screenshots found","files":[]},{"name":"Visual Polish","status":"skipped","result":"No screenshots to review","reasoning":"No screenshots found","files":[]},{"name":"Regression Detection","status":"skipped","result":"No screenshots to review","reasoning":"No screenshots found","files":[]}],"message":"No screenshots to review"}'
        else
          EXEC="${{ steps.review.outputs.execution_file }}"
          if [ -f "$EXEC" ]; then
            TEXT=$(jq -r '[.[] | select(.type=="assistant") | .message.content[]? | select(.type=="text") | .text] | last // ""' "$EXEC" 2>/dev/null || echo "")
            JSON=$(echo "$TEXT" | sed -n '/```json/,/```/{/```/d;p;}' | head -50)
            if echo "$JSON" | jq . >/dev/null 2>&1; then
              # Count checks by status
              CHECKS_PASSED=$(echo "$JSON" | jq '[.checks[]? | select(.status == "passed")] | length')
              CHECKS_FAILED=$(echo "$JSON" | jq '[.checks[]? | select(.status == "failed")] | length')
              CHECKS_SKIPPED=$(echo "$JSON" | jq '[.checks[]? | select(.status == "skipped")] | length')

              # Only pass if ALL checks passed (no failures)
              if [ "$CHECKS_FAILED" = "0" ] && [ "$CHECKS_PASSED" -gt "0" ]; then
                PASSED="true"
              elif [ "$CHECKS_FAILED" = "0" ] && [ "$CHECKS_PASSED" = "0" ] && [ "$CHECKS_SKIPPED" -gt "0" ]; then
                PASSED="true"
              fi

              RESULT=$(echo "$JSON" | jq -c '.')
            fi
          fi
        fi

        # Always output
        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "result=$RESULT" >> $GITHUB_OUTPUT
        echo "checks_passed=$CHECKS_PASSED" >> $GITHUB_OUTPUT
        echo "checks_failed=$CHECKS_FAILED" >> $GITHUB_OUTPUT
        echo "checks_skipped=$CHECKS_SKIPPED" >> $GITHUB_OUTPUT
