name: Consolidate Review Comment
description: Consolidates all review results into a single PR comment with dropdowns

inputs:
  review_results:
    description: 'JSON string containing all review results'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true

outputs:
  comment_id:
    description: 'ID of the created or updated comment'
    value: ${{ steps.comment.outputs.comment_id }}
  comment_url:
    description: 'URL of the comment'
    value: ${{ steps.comment.outputs.comment_url }}

runs:
  using: composite
  steps:
    - name: Find and update or create comment
      id: comment
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REVIEW_RESULTS: ${{ inputs.review_results }}
      run: |
        # Constants
        COMMENT_MARKER="<!-- ci-review-comment -->"

        # Parse review results
        echo "$REVIEW_RESULTS" > /tmp/review_results.json

        # Extract individual review data with defaults
        REQUIREMENTS=$(echo "$REVIEW_RESULTS" | jq -r '.requirements // {}')
        RULES=$(echo "$REVIEW_RESULTS" | jq -r '.rules // {}')
        PROJECT_MEMORY=$(echo "$REVIEW_RESULTS" | jq -r '.project_memory // {}')
        AGENTS=$(echo "$REVIEW_RESULTS" | jq -r '.agents // {}')
        SKILLS=$(echo "$REVIEW_RESULTS" | jq -r '.skills // {}')
        UI=$(echo "$REVIEW_RESULTS" | jq -r '.ui // {}')

        # Get commit SHA
        COMMIT_SHA="${{ github.sha }}"
        SHORT_SHA="${COMMIT_SHA:0:7}"

        # Count passed/total reviews
        TOTAL=0
        PASSED=0

        count_review() {
          local review="$1"
          local status=$(echo "$review" | jq -r '.status // "skipped"')
          if [ "$status" != "skipped" ]; then
            TOTAL=$((TOTAL + 1))
            if [ "$status" = "passed" ]; then
              PASSED=$((PASSED + 1))
            fi
          fi
        }

        count_review "$REQUIREMENTS"
        count_review "$RULES"
        count_review "$PROJECT_MEMORY"
        count_review "$AGENTS"
        count_review "$SKILLS"
        count_review "$UI"

        # Helper function to generate status indicator
        get_status_indicator() {
          local status="$1"
          local confidence="$2"

          case "$status" in
            "passed")
              echo "PASSED | Confidence: $confidence"
              ;;
            "failed")
              echo "FAILED | Confidence: $confidence"
              ;;
            "skipped")
              echo "Skipped"
              ;;
            *)
              echo "Unknown"
              ;;
          esac
        }

        # Helper function to generate dropdown section
        generate_dropdown() {
          local title="$1"
          local review_json="$2"
          local skip_reason="$3"

          local status=$(echo "$review_json" | jq -r '.status // "skipped"')
          local confidence=$(echo "$review_json" | jq -r '.confidence // 0')
          local summary=$(echo "$review_json" | jq -r '.summary // ""')
          local content=$(echo "$review_json" | jq -r '.content // ""')

          if [ "$status" = "skipped" ]; then
            cat <<DROPDOWN
        <details>
        <summary>$title -- Skipped</summary>

        ${skip_reason:-No relevant files were modified.}

        </details>
        DROPDOWN
          else
            local status_icon
            if [ "$status" = "passed" ]; then
              status_icon="PASSED"
            else
              status_icon="FAILED"
            fi

            cat <<DROPDOWN
        <details>
        <summary>$title $status_icon | Confidence: $confidence</summary>

        ### Summary
        $summary

        $content

        </details>
        DROPDOWN
          fi
        }

        # Generate requirements section content
        generate_requirements_content() {
          local review_json="$1"
          local status=$(echo "$review_json" | jq -r '.status // "skipped"')

          if [ "$status" = "skipped" ]; then
            return
          fi

          local met=$(echo "$review_json" | jq -r '.requirements_met // []')
          local missing=$(echo "$review_json" | jq -r '.requirements_missing // []')

          local content=""

          if [ "$met" != "[]" ] && [ "$met" != "null" ]; then
            content="${content}
        ### Requirements Met"
            while IFS= read -r req; do
              if [ -n "$req" ] && [ "$req" != "null" ]; then
                content="${content}
        - $req"
              fi
            done < <(echo "$met" | jq -r '.[]')
          fi

          if [ "$missing" != "[]" ] && [ "$missing" != "null" ]; then
            content="${content}

        ### Requirements Missing"
            while IFS= read -r req; do
              if [ -n "$req" ] && [ "$req" != "null" ]; then
                content="${content}
        - $req"
              fi
            done < <(echo "$missing" | jq -r '.[]')
          fi

          echo "$content"
        }

        # Generate UI section content with scores table
        generate_ui_content() {
          local review_json="$1"
          local status=$(echo "$review_json" | jq -r '.status // "skipped"')

          if [ "$status" = "skipped" ]; then
            return
          fi

          local bp=$(echo "$review_json" | jq -r '.best_practices_evaluation // {}')
          local critical=$(echo "$review_json" | jq -r '.total_critical // 0')
          local major=$(echo "$review_json" | jq -r '.total_major // 0')
          local minor=$(echo "$review_json" | jq -r '.total_minor // 0')
          local recs=$(echo "$review_json" | jq -r '.top_recommendations // []')

          local content="
        ### Issue Summary
        | Level | Count |
        |-------|-------|
        | Critical | $critical |
        | Major | $major |
        | Minor | $minor |"

          if [ "$bp" != "{}" ] && [ "$bp" != "null" ]; then
            local visual=$(echo "$bp" | jq -r '.visual_design // "N/A"')
            local layout=$(echo "$bp" | jq -r '.layout_responsiveness // "N/A"')
            local a11y=$(echo "$bp" | jq -r '.accessibility // "N/A"')
            local ux=$(echo "$bp" | jq -r '.user_experience // "N/A"')
            local elegance=$(echo "$bp" | jq -r '.modern_elegance // "N/A"')

            content="${content}

        ### Best Practices Scores
        | Category | Score |
        |----------|-------|
        | Visual Design | ${visual}/10 |
        | Layout & Responsiveness | ${layout}/10 |
        | Accessibility | ${a11y}/10 |
        | User Experience | ${ux}/10 |
        | Modern Elegance | ${elegance}/10 |"
          fi

          if [ "$recs" != "[]" ] && [ "$recs" != "null" ]; then
            content="${content}

        ### Top Recommendations"
            local i=1
            while IFS= read -r rec; do
              if [ -n "$rec" ] && [ "$rec" != "null" ]; then
                content="${content}
        $i. $rec"
                i=$((i + 1))
              fi
            done < <(echo "$recs" | jq -r '.[]')
          fi

          echo "$content"
        }

        # Build the complete comment body
        build_comment_body() {
          # Requirements section
          local req_status=$(echo "$REQUIREMENTS" | jq -r '.status // "skipped"')
          local req_confidence=$(echo "$REQUIREMENTS" | jq -r '.confidence // 0')
          local req_summary=$(echo "$REQUIREMENTS" | jq -r '.summary // ""')
          local req_content=$(generate_requirements_content "$REQUIREMENTS")

          local requirements_section
          if [ "$req_status" = "skipped" ]; then
            requirements_section="<details>
        <summary>Requirements Review -- Skipped</summary>

        No linked issue found or no requirements to verify.

        </details>"
          else
            local req_icon
            if [ "$req_status" = "passed" ]; then
              req_icon="PASSED"
            else
              req_icon="FAILED"
            fi
            requirements_section="<details>
        <summary>Requirements Review $req_icon | Confidence: $req_confidence</summary>

        ### Summary
        $req_summary
        $req_content

        </details>"
          fi

          # Rules section
          local rules_status=$(echo "$RULES" | jq -r '.status // "skipped"')
          local rules_confidence=$(echo "$RULES" | jq -r '.confidence // 0')
          local rules_summary=$(echo "$RULES" | jq -r '.summary // ""')
          local rules_content=$(echo "$RULES" | jq -r '.content // ""')

          local rules_section
          if [ "$rules_status" = "skipped" ]; then
            rules_section="<details>
        <summary>Rules Review -- Skipped</summary>

        No rules files found or no applicable rules.

        </details>"
          else
            local rules_icon
            if [ "$rules_status" = "passed" ]; then
              rules_icon="PASSED"
            else
              rules_icon="FAILED"
            fi
            rules_section="<details>
        <summary>Rules Review $rules_icon | Confidence: $rules_confidence</summary>

        ### Summary
        $rules_summary

        $rules_content

        </details>"
          fi

          # Project Memory section
          local pm_status=$(echo "$PROJECT_MEMORY" | jq -r '.status // "skipped"')
          local pm_confidence=$(echo "$PROJECT_MEMORY" | jq -r '.confidence // 0')
          local pm_summary=$(echo "$PROJECT_MEMORY" | jq -r '.summary // ""')
          local pm_content=$(echo "$PROJECT_MEMORY" | jq -r '.content // ""')

          local pm_section
          if [ "$pm_status" = "skipped" ]; then
            pm_section="<details>
        <summary>Project Memory Review -- Skipped</summary>

        No CLAUDE.md files were modified.

        </details>"
          else
            local pm_icon
            if [ "$pm_status" = "passed" ]; then
              pm_icon="PASSED"
            else
              pm_icon="FAILED"
            fi
            pm_section="<details>
        <summary>Project Memory Review $pm_icon | Confidence: $pm_confidence</summary>

        ### Summary
        $pm_summary

        $pm_content

        </details>"
          fi

          # Agents section
          local agents_status=$(echo "$AGENTS" | jq -r '.status // "skipped"')
          local agents_confidence=$(echo "$AGENTS" | jq -r '.confidence // 0')
          local agents_summary=$(echo "$AGENTS" | jq -r '.summary // ""')
          local agents_content=$(echo "$AGENTS" | jq -r '.content // ""')

          local agents_section
          if [ "$agents_status" = "skipped" ]; then
            agents_section="<details>
        <summary>Agents Review -- Skipped</summary>

        No agent files were modified.

        </details>"
          else
            local agents_icon
            if [ "$agents_status" = "passed" ]; then
              agents_icon="PASSED"
            else
              agents_icon="FAILED"
            fi
            agents_section="<details>
        <summary>Agents Review $agents_icon | Confidence: $agents_confidence</summary>

        ### Summary
        $agents_summary

        $agents_content

        </details>"
          fi

          # Skills section
          local skills_status=$(echo "$SKILLS" | jq -r '.status // "skipped"')
          local skills_confidence=$(echo "$SKILLS" | jq -r '.confidence // 0')
          local skills_summary=$(echo "$SKILLS" | jq -r '.summary // ""')
          local skills_content=$(echo "$SKILLS" | jq -r '.content // ""')

          local skills_section
          if [ "$skills_status" = "skipped" ]; then
            skills_section="<details>
        <summary>Skills Review -- Skipped</summary>

        No skill files were modified.

        </details>"
          else
            local skills_icon
            if [ "$skills_status" = "passed" ]; then
              skills_icon="PASSED"
            else
              skills_icon="FAILED"
            fi
            skills_section="<details>
        <summary>Skills Review $skills_icon | Confidence: $skills_confidence</summary>

        ### Summary
        $skills_summary

        $skills_content

        </details>"
          fi

          # UI section
          local ui_status=$(echo "$UI" | jq -r '.status // "skipped"')
          local ui_confidence=$(echo "$UI" | jq -r '.confidence // 0')
          local ui_summary=$(echo "$UI" | jq -r '.summary // ""')
          local ui_content=$(generate_ui_content "$UI")

          local ui_section
          if [ "$ui_status" = "skipped" ]; then
            ui_section="<details>
        <summary>UI Review -- Skipped</summary>

        No UI files were modified.

        </details>"
          else
            local ui_icon
            if [ "$ui_status" = "passed" ]; then
              ui_icon="PASSED"
            else
              ui_icon="FAILED"
            fi
            ui_section="<details>
        <summary>UI Review $ui_icon | Confidence: $ui_confidence</summary>

        ### Summary
        $ui_summary
        $ui_content

        </details>"
          fi

          # Combine all sections
          cat <<COMMENT
        $COMMENT_MARKER
        ## Code Review Results

        **Commit:** \`$SHORT_SHA\` | **Status:** $PASSED/$TOTAL Passed

        ---

        $requirements_section

        $rules_section

        $pm_section

        $agents_section

        $skills_section

        $ui_section

        ---

        *Automated by Claude Code CI*
        COMMENT
        }

        # Build the comment body
        COMMENT_BODY=$(build_comment_body)

        # Save comment body to file for API call
        echo "$COMMENT_BODY" > /tmp/comment_body.md

        # Get PR number
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          PR_NUMBER="${{ github.event.pull_request.number }}"
        else
          # Try to find PR for this commit
          PR_NUMBER=$(gh pr list --state open --json number,headRefName --jq ".[] | select(.headRefName == \"${{ github.ref_name }}\") | .number" 2>/dev/null || echo "")
        fi

        if [ -z "$PR_NUMBER" ]; then
          echo "No PR found, skipping comment"
          echo "comment_id=" >> $GITHUB_OUTPUT
          echo "comment_url=" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Find existing comment with marker
        EXISTING_COMMENT_ID=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
          --jq ".[] | select(.body | contains(\"$COMMENT_MARKER\")) | .id" \
          2>/dev/null | head -1)

        if [ -n "$EXISTING_COMMENT_ID" ]; then
          # Update existing comment
          RESPONSE=$(gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/issues/comments/${EXISTING_COMMENT_ID}" \
            -f body="$(cat /tmp/comment_body.md)")

          COMMENT_ID="$EXISTING_COMMENT_ID"
          COMMENT_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          echo "Updated existing comment: $COMMENT_ID"
        else
          # Create new comment
          RESPONSE=$(gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
            -f body="$(cat /tmp/comment_body.md)")

          COMMENT_ID=$(echo "$RESPONSE" | jq -r '.id')
          COMMENT_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          echo "Created new comment: $COMMENT_ID"
        fi

        echo "comment_id=$COMMENT_ID" >> $GITHUB_OUTPUT
        echo "comment_url=$COMMENT_URL" >> $GITHUB_OUTPUT
