name: Sync Constellos Review Workflow
description: Fetches the latest constellos-review.yml template and updates the local copy if outdated

inputs:
  workflow_path:
    description: Path to the local workflow file to sync
    required: false
    default: .github/workflows/constellos-review.yml
  template_url:
    description: URL to fetch the latest template from
    required: false
    default: https://raw.githubusercontent.com/constellos/github-agents/main/.github/templates/constellos-review.yml

runs:
  using: composite
  steps:
    - name: Sync workflow file
      shell: bash
      env:
        WORKFLOW_PATH: ${{ inputs.workflow_path }}
        TEMPLATE_URL: ${{ inputs.template_url }}
      run: |
        echo "::group::Sync constellos-review.yml"

        # Fetch latest template
        LATEST=$(curl -fsSL "$TEMPLATE_URL" 2>&1) || {
          echo "::warning::Failed to fetch latest template from $TEMPLATE_URL"
          echo "::endgroup::"
          exit 0
        }

        # Compare with local copy
        if [ -f "$WORKFLOW_PATH" ]; then
          LOCAL=$(cat "$WORKFLOW_PATH")
          if [ "$LATEST" = "$LOCAL" ]; then
            echo "Workflow is up to date."
            echo "::endgroup::"
            exit 0
          fi
        fi

        echo "Workflow is outdated — updating."
        mkdir -p "$(dirname "$WORKFLOW_PATH")"
        echo "$LATEST" > "$WORKFLOW_PATH"

        # Configure git and push
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add "$WORKFLOW_PATH"
        git commit -m "chore: sync constellos-review.yml from template" || {
          echo "::warning::Nothing to commit (file unchanged after write)."
          echo "::endgroup::"
          exit 0
        }
        git push || {
          echo "::warning::Failed to push workflow sync commit. The PR branch may be from a fork."
          echo "::endgroup::"
          exit 0
        }

        echo "Workflow synced successfully."
        echo "::endgroup::"
