name: Context Reviewer
description: AI-powered PR context review - analyzes PR for completeness and clarity (stub)

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  claude_code_oauth_token:
    description: 'Claude Code OAuth token'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true

outputs:
  passed:
    description: 'Whether the review passed (all checks passed)'
    value: ${{ steps.result.outputs.passed }}
  skipped:
    description: 'Whether the review was skipped'
    value: ${{ steps.result.outputs.skipped }}
  result:
    description: 'JSON result from the review'
    value: ${{ steps.result.outputs.result }}
  checks_passed:
    description: 'Number of checks that passed'
    value: ${{ steps.result.outputs.checks_passed }}
  checks_failed:
    description: 'Number of checks that failed'
    value: ${{ steps.result.outputs.checks_failed }}
  checks_skipped:
    description: 'Number of checks that were skipped'
    value: ${{ steps.result.outputs.checks_skipped }}

runs:
  using: composite
  steps:
    - name: Get context
      id: context
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        mkdir -p .claude/review-context

        # Get changed files
        gh pr view ${{ inputs.pr_number }} --json files --jq '.files[].path' > .claude/review-context/changed.txt 2>/dev/null || touch .claude/review-context/changed.txt

        # Get PR details
        gh pr view ${{ inputs.pr_number }} --json title,body,author > .claude/review-context/pr.json 2>/dev/null || echo '{}' > .claude/review-context/pr.json

        # Check if we have context
        if [ ! -s ".claude/review-context/changed.txt" ]; then
          echo "skip=true" >> $GITHUB_OUTPUT
          echo "skip_reason=No changed files found" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Load agent prompt
      id: agent
      if: steps.context.outputs.skip != 'true'
      shell: bash
      run: |
        if [ -f ".constellos/agents/context.md" ]; then
          PROMPT=$(cat .constellos/agents/context.md)
        else
          PROMPT="# Context Review

        Review the PR for context completeness and clarity.
        - Changed files: .claude/review-context/changed.txt
        - PR details: .claude/review-context/pr.json

        Evaluate:
        1. PR title is descriptive
        2. PR description explains the changes
        3. Changes are logically grouped

        Output json with checks array."
        fi

        echo "prompt<<ENDOFPROMPT" >> $GITHUB_OUTPUT
        echo "$PROMPT" >> $GITHUB_OUTPUT
        echo "ENDOFPROMPT" >> $GITHUB_OUTPUT

    - name: Run review
      id: review
      if: steps.context.outputs.skip != 'true'
      uses: anthropics/claude-code-base-action@main
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: ${{ steps.agent.outputs.prompt }}

    - name: Extract result
      id: result
      shell: bash
      run: |
        # Use shared extraction logic
        source "${{ github.action_path }}/../shared/extract-result.sh"

        # Handle skipped case
        if [ "${{ steps.context.outputs.skip }}" = "true" ]; then
          generate_skipped_result "${{ steps.context.outputs.skip_reason }}" \
            "Title" "Description" "Grouping"
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "skipped=true" >> $GITHUB_OUTPUT
          echo "result=$RESULT" >> $GITHUB_OUTPUT
          echo "checks_passed=$CHECKS_PASSED" >> $GITHUB_OUTPUT
          echo "checks_failed=$CHECKS_FAILED" >> $GITHUB_OUTPUT
          echo "checks_skipped=$CHECKS_SKIPPED" >> $GITHUB_OUTPUT
          exit 0
        fi

        extract_review_result "${{ steps.review.outputs.execution_file }}"

        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "skipped=false" >> $GITHUB_OUTPUT
        echo "result=$RESULT" >> $GITHUB_OUTPUT
        echo "checks_passed=$CHECKS_PASSED" >> $GITHUB_OUTPUT
        echo "checks_failed=$CHECKS_FAILED" >> $GITHUB_OUTPUT
        echo "checks_skipped=$CHECKS_SKIPPED" >> $GITHUB_OUTPUT
