name: Code Quality Reviewer
description: AI code quality review for DRY, YAGNI, modularity using Claude

branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  claude_code_oauth_token:
    description: 'Claude Code OAuth token'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true

outputs:
  passed:
    description: 'Whether the review passed (all checks passed)'
    value: ${{ steps.extract.outputs.passed }}
  result:
    description: 'JSON result from the review'
    value: ${{ steps.extract.outputs.result }}
  checks_passed:
    description: 'Number of checks that passed'
    value: ${{ steps.extract.outputs.checks_passed }}
  checks_failed:
    description: 'Number of checks that failed'
    value: ${{ steps.extract.outputs.checks_failed }}
  checks_skipped:
    description: 'Number of checks that were skipped'
    value: ${{ steps.extract.outputs.checks_skipped }}

runs:
  using: composite
  steps:
    - name: Get changed files
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        mkdir -p .claude/review-context
        # Gracefully handle permission errors
        gh pr view ${{ inputs.pr_number }} --json files --jq '.files[].path' > .claude/review-context/changed.txt 2>/dev/null || touch .claude/review-context/changed.txt

    - name: Validate context
      id: validate
      shell: bash
      run: |
        SKIP="false"
        SKIP_REASON=""
        if [ ! -s ".claude/review-context/changed.txt" ]; then
          SKIP="true"
          SKIP_REASON="No changed files found or unable to access PR data"
        fi
        echo "skip=$SKIP" >> $GITHUB_OUTPUT
        echo "skip_reason=$SKIP_REASON" >> $GITHUB_OUTPUT

    - name: Load agent prompt
      id: agent
      shell: bash
      run: |
        if [ -f ".constellos/agents/code-quality.md" ]; then
          PROMPT=$(cat .constellos/agents/code-quality.md)
        else
          PROMPT='# Code Quality Review

        Review the changed files in .claude/review-context/changed.txt for code quality.

        ## Checks to Perform
        Evaluate each criterion and output a JSON object with a checks array:

        1. **DRY Compliance** - No unnecessary code duplication
        2. **YAGNI Compliance** - No speculative features or over-engineering
        3. **Modularity** - Appropriate separation of concerns
        4. **Maintainability** - Clear, readable, well-structured code

        ## Required Output Format
        ```json
        {
          "checks": [
            {
              "name": "DRY Compliance",
              "status": "passed",
              "reasoning": "Brief explanation of why this passed or failed",
              "files": []
            },
            {
              "name": "YAGNI Compliance",
              "status": "passed",
              "reasoning": "Brief explanation",
              "files": []
            },
            {
              "name": "Modularity",
              "status": "passed",
              "reasoning": "Brief explanation",
              "files": []
            },
            {
              "name": "Maintainability",
              "status": "passed",
              "reasoning": "Brief explanation",
              "files": []
            }
          ]
        }
        ```

        Set status to "passed" if the code meets the criterion, "failed" if issues found, "skipped" if not applicable.
        For failed checks, include files array with specific locations: [{"path": "file.ts", "line": 42, "note": "Issue description"}]'
        fi

        echo "prompt<<ENDOFPROMPT" >> $GITHUB_OUTPUT
        echo "$PROMPT" >> $GITHUB_OUTPUT
        echo "ENDOFPROMPT" >> $GITHUB_OUTPUT

    - name: Run review
      id: review
      if: steps.validate.outputs.skip != 'true'
      uses: anthropics/claude-code-base-action@main
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: ${{ steps.agent.outputs.prompt }}

    - name: Extract result
      id: extract
      shell: bash
      run: |
        # Use shared extraction logic
        source "${{ github.action_path }}/../shared/extract-result.sh"

        # Handle skipped case first
        if [ "${{ steps.validate.outputs.skip }}" = "true" ]; then
          generate_skipped_result "${{ steps.validate.outputs.skip_reason }}" \
            "DRY Compliance" "YAGNI Compliance" "Modularity" "Maintainability"
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "result=$RESULT" >> $GITHUB_OUTPUT
          echo "checks_passed=$CHECKS_PASSED" >> $GITHUB_OUTPUT
          echo "checks_failed=$CHECKS_FAILED" >> $GITHUB_OUTPUT
          echo "checks_skipped=$CHECKS_SKIPPED" >> $GITHUB_OUTPUT
          exit 0
        fi

        extract_review_result "${{ steps.review.outputs.execution_file }}"

        # Always output
        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "result=$RESULT" >> $GITHUB_OUTPUT
        echo "checks_passed=$CHECKS_PASSED" >> $GITHUB_OUTPUT
        echo "checks_failed=$CHECKS_FAILED" >> $GITHUB_OUTPUT
        echo "checks_skipped=$CHECKS_SKIPPED" >> $GITHUB_OUTPUT
