name: Create Check Run
description: Creates or updates a GitHub check run for agent results

branding:
  icon: 'check-square'
  color: 'green'

inputs:
  name:
    description: 'Name of the check run (e.g., "Requirements Review")'
    required: true
  sha:
    description: 'Commit SHA to attach the check to'
    required: true
  status:
    description: 'Check status: queued, in_progress, or completed'
    required: false
    default: 'completed'
  conclusion:
    description: 'Conclusion when completed: success, failure, neutral, cancelled, skipped, timed_out, action_required'
    required: false
    default: 'neutral'
  title:
    description: 'Title for the check run output'
    required: false
    default: ''
  summary:
    description: 'Summary markdown for the check run output'
    required: false
    default: ''
  details_url:
    description: 'URL for more details'
    required: false
    default: ''
  github_token:
    description: 'GitHub token with checks:write permission'
    required: true
  check_run_id:
    description: 'Existing check run ID to update (optional - creates new if not provided)'
    required: false
    default: ''

outputs:
  check_run_id:
    description: 'ID of the created/updated check run'
    value: ${{ steps.check.outputs.check_run_id }}
  check_run_url:
    description: 'URL of the check run'
    value: ${{ steps.check.outputs.check_run_url }}

runs:
  using: composite
  steps:
    - name: Create or update check run
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        NAME="${{ inputs.name }}"
        SHA="${{ inputs.sha }}"
        STATUS="${{ inputs.status }}"
        CONCLUSION="${{ inputs.conclusion }}"
        TITLE="${{ inputs.title }}"
        SUMMARY="${{ inputs.summary }}"
        DETAILS_URL="${{ inputs.details_url }}"
        CHECK_RUN_ID="${{ inputs.check_run_id }}"

        # Build the output object if title/summary provided
        OUTPUT_JSON=""
        if [ -n "$TITLE" ] || [ -n "$SUMMARY" ]; then
          OUTPUT_JSON=$(jq -n \
            --arg title "${TITLE:-$NAME}" \
            --arg summary "${SUMMARY:-No summary provided}" \
            '{title: $title, summary: $summary}')
        fi

        if [ -n "$CHECK_RUN_ID" ]; then
          # Update existing check run
          API_PATH="repos/${{ github.repository }}/check-runs/${CHECK_RUN_ID}"
          METHOD="PATCH"

          if [ "$STATUS" = "completed" ]; then
            BODY=$(jq -n \
              --arg status "$STATUS" \
              --arg conclusion "$CONCLUSION" \
              --argjson output "${OUTPUT_JSON:-null}" \
              '{status: $status, conclusion: $conclusion} + (if $output then {output: $output} else {} end)')
          else
            BODY=$(jq -n \
              --arg status "$STATUS" \
              --argjson output "${OUTPUT_JSON:-null}" \
              '{status: $status} + (if $output then {output: $output} else {} end)')
          fi
        else
          # Create new check run
          API_PATH="repos/${{ github.repository }}/check-runs"
          METHOD="POST"

          if [ "$STATUS" = "completed" ]; then
            BODY=$(jq -n \
              --arg name "$NAME" \
              --arg head_sha "$SHA" \
              --arg status "$STATUS" \
              --arg conclusion "$CONCLUSION" \
              --arg details_url "$DETAILS_URL" \
              --argjson output "${OUTPUT_JSON:-null}" \
              '{name: $name, head_sha: $head_sha, status: $status, conclusion: $conclusion} + (if $details_url != "" then {details_url: $details_url} else {} end) + (if $output then {output: $output} else {} end)')
          else
            BODY=$(jq -n \
              --arg name "$NAME" \
              --arg head_sha "$SHA" \
              --arg status "$STATUS" \
              --arg details_url "$DETAILS_URL" \
              --argjson output "${OUTPUT_JSON:-null}" \
              '{name: $name, head_sha: $head_sha, status: $status} + (if $details_url != "" then {details_url: $details_url} else {} end) + (if $output then {output: $output} else {} end)')
          fi
        fi

        echo "Request body:"
        echo "$BODY" | jq .

        RESPONSE=$(gh api -X "$METHOD" "$API_PATH" --input - <<< "$BODY")

        CHECK_ID=$(echo "$RESPONSE" | jq -r '.id')
        CHECK_URL=$(echo "$RESPONSE" | jq -r '.html_url')

        echo "check_run_id=$CHECK_ID" >> $GITHUB_OUTPUT
        echo "check_run_url=$CHECK_URL" >> $GITHUB_OUTPUT

        echo "Check run created/updated: $CHECK_URL"
