name: Detect Changed Files
description: Smart file change detection for efficient CI

inputs:
  pattern:
    description: 'Regex pattern to filter files'
    required: false
    default: '.*'

outputs:
  changed_files:
    description: 'Newline-separated list of changed files'
    value: ${{ steps.detect.outputs.changed_files }}
  has_changes:
    description: 'Whether any matching files changed'
    value: ${{ steps.detect.outputs.has_changes }}
  file_count:
    description: 'Number of changed files'
    value: ${{ steps.detect.outputs.file_count }}
  has_ts_files:
    description: 'Whether any TypeScript files changed'
    value: ${{ steps.detect.outputs.has_ts_files }}
  has_test_files:
    description: 'Whether any test files changed'
    value: ${{ steps.detect.outputs.has_test_files }}
  ts_files:
    description: 'List of TypeScript files'
    value: ${{ steps.detect.outputs.ts_files }}
  test_files:
    description: 'List of test files'
    value: ${{ steps.detect.outputs.test_files }}

runs:
  using: composite
  steps:
    - name: Detect changed files
      id: detect
      shell: bash
      run: |
        # Get changed files based on event type
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          CHANGED=$(git diff --name-only \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.sha }})
        elif [ "${{ github.event_name }}" = "push" ]; then
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            # New branch
            CHANGED=$(git diff --name-only origin/main...HEAD 2>/dev/null || git ls-files)
          else
            CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi
        else
          CHANGED=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || git ls-files)
        fi

        # Apply pattern filter
        PATTERN="${{ inputs.pattern }}"
        if [ "$PATTERN" != ".*" ]; then
          FILTERED=$(echo "$CHANGED" | grep -E "$PATTERN" || echo "")
        else
          FILTERED="$CHANGED"
        fi

        # TypeScript files
        TS_FILES=$(echo "$CHANGED" | grep -E '\.(ts|tsx)$' || echo "")

        # Test files
        TEST_FILES=$(echo "$CHANGED" | grep -E '\.(test|spec)\.(ts|tsx|js|jsx)$' || echo "")

        # Count and flags
        if [ -n "$FILTERED" ]; then
          COUNT=$(echo "$FILTERED" | wc -l)
          HAS_CHANGES='true'
        else
          COUNT=0
          HAS_CHANGES='false'
        fi

        if [ -n "$TS_FILES" ]; then
          HAS_TS='true'
        else
          HAS_TS='false'
        fi

        if [ -n "$TEST_FILES" ]; then
          HAS_TESTS='true'
        else
          HAS_TESTS='false'
        fi

        # Set outputs
        echo "changed_files<<EOF" >> $GITHUB_OUTPUT
        echo "$FILTERED" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        echo "ts_files<<EOF" >> $GITHUB_OUTPUT
        echo "$TS_FILES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        echo "test_files<<EOF" >> $GITHUB_OUTPUT
        echo "$TEST_FILES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        echo "has_changes=$HAS_CHANGES" >> $GITHUB_OUTPUT
        echo "file_count=$COUNT" >> $GITHUB_OUTPUT
        echo "has_ts_files=$HAS_TS" >> $GITHUB_OUTPUT
        echo "has_test_files=$HAS_TESTS" >> $GITHUB_OUTPUT
