# Constellos Review Workflow
# AI-powered code reviews on PRs using Claude
#
# This workflow is provisioned by the Constellos app.
# Configure agents via .constellos/config.json in your repo.

name: Constellos Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  # Read config and determine which agents to run
  config:
    runs-on: ubuntu-latest
    outputs:
      agents: ${{ steps.read.outputs.agents }}
    steps:
      - uses: actions/checkout@v4
      - id: read
        run: |
          if [ -f ".constellos/config.json" ]; then
            AGENTS=$(jq -c '[.agents | to_entries[] | select(.value.enabled) | .key]' .constellos/config.json)
          else
            # Default: run both agents
            AGENTS='["requirements","code-quality"]'
          fi
          echo "agents=$AGENTS" >> $GITHUB_OUTPUT

  # Run each enabled agent in parallel
  review:
    needs: config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        agent: ${{ fromJson(needs.config.outputs.agents) }}
    steps:
      - uses: actions/checkout@v4

      # Requirements reviewer
      - name: Run requirements review
        id: requirements
        if: matrix.agent == 'requirements'
        uses: constellos/github-agents/.github/actions/requirements-reviewer@main
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          pr_number: ${{ github.event.number }}
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send requirements results to webhook
        if: matrix.agent == 'requirements'
        env:
          RESULT_JSON: ${{ steps.requirements.outputs.result }}
        run: |
          # Build JSON payload safely using jq
          jq -n \
            --arg owner "${{ github.repository_owner }}" \
            --arg repo "${{ github.event.repository.name }}" \
            --argjson pr_number "${{ github.event.number }}" \
            --arg sha "${{ github.event.pull_request.head.sha }}" \
            --argjson run_id "${{ github.run_id }}" \
            --arg review_name "Requirements" \
            --argjson passed "${{ steps.requirements.outputs.passed }}" \
            --argjson result_json "$RESULT_JSON" \
            --argjson checks_passed "${{ steps.requirements.outputs.checks_passed || 0 }}" \
            --argjson checks_failed "${{ steps.requirements.outputs.checks_failed || 0 }}" \
            --argjson checks_skipped "${{ steps.requirements.outputs.checks_skipped || 0 }}" \
            --arg prompt_file ".constellos/agents/requirements.md" \
            '{
              owner: $owner,
              repo: $repo,
              pr_number: $pr_number,
              sha: $sha,
              run_id: $run_id,
              review_name: $review_name,
              results: {
                passed: $passed,
                result_json: $result_json,
                checks_passed: $checks_passed,
                checks_failed: $checks_failed,
                checks_skipped: $checks_skipped,
                prompt_file: $prompt_file
              }
            }' | curl -X POST "https://github.constellos.ai/results" \
              -H "Content-Type: application/json" \
              -d @-

      # Code quality reviewer
      - name: Run code-quality review
        id: code-quality
        if: matrix.agent == 'code-quality'
        uses: constellos/github-agents/.github/actions/code-quality-reviewer@main
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          pr_number: ${{ github.event.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send code-quality results to webhook
        if: matrix.agent == 'code-quality'
        env:
          RESULT_JSON: ${{ steps.code-quality.outputs.result }}
        run: |
          # Build JSON payload safely using jq
          jq -n \
            --arg owner "${{ github.repository_owner }}" \
            --arg repo "${{ github.event.repository.name }}" \
            --argjson pr_number "${{ github.event.number }}" \
            --arg sha "${{ github.event.pull_request.head.sha }}" \
            --argjson run_id "${{ github.run_id }}" \
            --arg review_name "Code Quality" \
            --argjson passed "${{ steps.code-quality.outputs.passed }}" \
            --argjson result_json "$RESULT_JSON" \
            --argjson checks_passed "${{ steps.code-quality.outputs.checks_passed || 0 }}" \
            --argjson checks_failed "${{ steps.code-quality.outputs.checks_failed || 0 }}" \
            --argjson checks_skipped "${{ steps.code-quality.outputs.checks_skipped || 0 }}" \
            --arg prompt_file ".constellos/agents/code-quality.md" \
            '{
              owner: $owner,
              repo: $repo,
              pr_number: $pr_number,
              sha: $sha,
              run_id: $run_id,
              review_name: $review_name,
              results: {
                passed: $passed,
                result_json: $result_json,
                checks_passed: $checks_passed,
                checks_failed: $checks_failed,
                checks_skipped: $checks_skipped,
                prompt_file: $prompt_file
              }
            }' | curl -X POST "https://github.constellos.ai/results" \
              -H "Content-Type: application/json" \
              -d @-

      # Context reviewer
      - name: Run context review
        id: context
        if: matrix.agent == 'context'
        uses: constellos/github-agents/.github/actions/context-reviewer@main
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          pr_number: ${{ github.event.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send context results to webhook
        if: matrix.agent == 'context'
        env:
          RESULT_JSON: ${{ steps.context.outputs.result }}
        run: |
          # Build JSON payload safely using jq
          jq -n \
            --arg owner "${{ github.repository_owner }}" \
            --arg repo "${{ github.event.repository.name }}" \
            --argjson pr_number "${{ github.event.number }}" \
            --arg sha "${{ github.event.pull_request.head.sha }}" \
            --argjson run_id "${{ github.run_id }}" \
            --arg review_name "Context" \
            --argjson passed "${{ steps.context.outputs.passed }}" \
            --argjson result_json "$RESULT_JSON" \
            --argjson checks_passed "${{ steps.context.outputs.checks_passed || 0 }}" \
            --argjson checks_failed "${{ steps.context.outputs.checks_failed || 0 }}" \
            --argjson checks_skipped "${{ steps.context.outputs.checks_skipped || 0 }}" \
            --arg prompt_file ".constellos/agents/context.md" \
            '{
              owner: $owner,
              repo: $repo,
              pr_number: $pr_number,
              sha: $sha,
              run_id: $run_id,
              review_name: $review_name,
              results: {
                passed: $passed,
                result_json: $result_json,
                checks_passed: $checks_passed,
                checks_failed: $checks_failed,
                checks_skipped: $checks_skipped,
                prompt_file: $prompt_file
              }
            }' | curl -X POST "https://github.constellos.ai/results" \
              -H "Content-Type: application/json" \
              -d @-
