# Constellos Review Workflow
# AI-powered code reviews on PRs using Claude
#
# This workflow is provisioned by the Constellos app.
# Configure agents via .constellos/config.json in your repo.

name: Constellos Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: read
  pull-requests: write

jobs:
  # Read config and determine which agents to run
  config:
    runs-on: ubuntu-latest
    outputs:
      agents: ${{ steps.read.outputs.agents }}
    steps:
      - uses: actions/checkout@v4
      - id: read
        run: |
          if [ -f ".constellos/config.json" ]; then
            AGENTS=$(jq -c '[.agents | to_entries[] | select(.value.enabled) | .key]' .constellos/config.json)
          else
            # Default: run both agents
            AGENTS='["requirements","code-quality"]'
          fi
          echo "agents=$AGENTS" >> $GITHUB_OUTPUT

  # Run each enabled agent in parallel
  review:
    needs: config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        agent: ${{ fromJson(needs.config.outputs.agents) }}
    steps:
      - uses: actions/checkout@v4

      # Requirements reviewer
      - name: Run requirements review
        id: requirements
        if: matrix.agent == 'requirements'
        uses: constellos/github-agents/.github/actions/requirements-reviewer@main
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          pr_number: ${{ github.event.number }}
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post requirements comment
        if: matrix.agent == 'requirements'
        uses: constellos/github-agents/.github/actions/review-comment@main
        with:
          review_name: Requirements
          passed: ${{ steps.requirements.outputs.passed }}
          result_json: ${{ steps.requirements.outputs.result }}
          checks_passed: ${{ steps.requirements.outputs.checks_passed }}
          checks_failed: ${{ steps.requirements.outputs.checks_failed }}
          checks_skipped: ${{ steps.requirements.outputs.checks_skipped }}
          pr_number: ${{ github.event.number }}
          sha: ${{ github.event.pull_request.head.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt_file: .constellos/agents/requirements.md

      # Code quality reviewer
      - name: Run code-quality review
        id: code-quality
        if: matrix.agent == 'code-quality'
        uses: constellos/github-agents/.github/actions/code-quality-reviewer@main
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          pr_number: ${{ github.event.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post code-quality comment
        if: matrix.agent == 'code-quality'
        uses: constellos/github-agents/.github/actions/review-comment@main
        with:
          review_name: Code Quality
          passed: ${{ steps.code-quality.outputs.passed }}
          result_json: ${{ steps.code-quality.outputs.result }}
          checks_passed: ${{ steps.code-quality.outputs.checks_passed }}
          checks_failed: ${{ steps.code-quality.outputs.checks_failed }}
          checks_skipped: ${{ steps.code-quality.outputs.checks_skipped }}
          pr_number: ${{ github.event.number }}
          sha: ${{ github.event.pull_request.head.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt_file: .constellos/agents/code-quality.md

      # Context reviewer
      - name: Run context review
        id: context
        if: matrix.agent == 'context'
        uses: constellos/github-agents/.github/actions/context-reviewer@main
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          pr_number: ${{ github.event.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post context comment
        if: matrix.agent == 'context'
        uses: constellos/github-agents/.github/actions/review-comment@main
        with:
          review_name: Context
          passed: ${{ steps.context.outputs.passed }}
          result_json: ${{ steps.context.outputs.result }}
          checks_passed: ${{ steps.context.outputs.checks_passed }}
          checks_failed: ${{ steps.context.outputs.checks_failed }}
          checks_skipped: ${{ steps.context.outputs.checks_skipped }}
          pr_number: ${{ github.event.number }}
          sha: ${{ github.event.pull_request.head.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt_file: .constellos/agents/context.md
