# Constellos Review Workflow Template
# Copy this file to your repo's .github/workflows/ directory
#
# Prerequisites:
# 1. Add CLAUDE_CODE_OAUTH_TOKEN secret to your repo
# 2. (Optional) Create .constellos/config.json to customize agents

name: Constellos Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    uses: constellos/github-agents/.github/workflows/review.yml@main
    with:
      pr_number: ${{ github.event.number }}
      sha: ${{ github.event.pull_request.head.sha }}
      branch: ${{ github.head_ref }}
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
