# =============================================================================
# CI Configuration Template: Supabase + Vercel
# =============================================================================
#
# Use this template for:
#   - Next.js applications with Supabase backend
#   - Full-stack apps using Supabase Auth, Database, or Storage
#   - Projects requiring both Vercel preview deploys and Supabase migrations
#   - Apps with E2E tests that need database seeding
#
# To use: Copy this file to your repo root as `.github/ci-config.yml`
#
# Note: Ensure you have SUPABASE_ACCESS_TOKEN and project secrets configured
# =============================================================================

ci:
  # ---------------------------------------------------------------------------
  # Basic CI Checks
  # ---------------------------------------------------------------------------
  # These run on every PR and push to ensure code quality
  basic:
    enabled: true
    lint: true          # Run ESLint to catch code issues
    typecheck: true     # Run TypeScript compiler for type safety
    vitest: true        # Run unit/integration tests with Vitest

  # ---------------------------------------------------------------------------
  # End-to-End Testing
  # ---------------------------------------------------------------------------
  # Playwright tests run against the deployed preview with Supabase
  e2e:
    enabled: true
    framework: playwright
    wait_for_deployment: true   # Wait for Vercel preview before running tests

  # ---------------------------------------------------------------------------
  # AI-Powered Code Reviews
  # ---------------------------------------------------------------------------
  # Claude Code reviews PRs based on configured rules and context
  reviews:
    enabled: true
    requirements: true      # Check PR against project requirements
    rules: true             # Enforce coding standards from .claude/rules/
    project_memory: true    # Use project context for smarter reviews
    agents: true            # Enable multi-agent review capabilities
    skills: true            # Use specialized review skills
    playwright_ui: true     # AI reviews UI changes via Playwright screenshots

  # ---------------------------------------------------------------------------
  # Deployment Configuration
  # ---------------------------------------------------------------------------
  # Configure your deployment platform(s)
  deployment:
    enabled: true
    vercel:
      enabled: true         # Deploy previews and production to Vercel
    supabase:
      enabled: true         # Enable Supabase migrations and preview branches
      # Supabase will:
      # - Create preview branches for PR previews
      # - Run database migrations automatically
      # - Seed test data for E2E tests (if configured)
    cloudflare:
      enabled: false        # Not using Cloudflare for this setup
