# =============================================================================
# CI Configuration Template: Cloudflare Pages
# =============================================================================
#
# Use this template for:
#   - Applications deployed to Cloudflare Pages
#   - Static sites, SSR apps, or full-stack apps on Cloudflare
#   - Projects using Cloudflare Workers or D1 database
#   - Apps that want edge-first deployment
#
# To use: Copy this file to your repo root as `.github/ci-config.yml`
#
# Note: Ensure you have CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID configured
# =============================================================================

ci:
  # ---------------------------------------------------------------------------
  # Basic CI Checks
  # ---------------------------------------------------------------------------
  # These run on every PR and push to ensure code quality
  basic:
    enabled: true
    lint: true          # Run ESLint to catch code issues
    typecheck: true     # Run TypeScript compiler for type safety
    vitest: true        # Run unit/integration tests with Vitest

  # ---------------------------------------------------------------------------
  # End-to-End Testing
  # ---------------------------------------------------------------------------
  # Playwright tests run against the deployed preview
  e2e:
    enabled: true
    framework: playwright
    wait_for_deployment: true   # Wait for Cloudflare preview before running tests

  # ---------------------------------------------------------------------------
  # AI-Powered Code Reviews
  # ---------------------------------------------------------------------------
  # Claude Code reviews PRs based on configured rules and context
  reviews:
    enabled: true
    requirements: true      # Check PR against project requirements
    rules: true             # Enforce coding standards from .claude/rules/
    project_memory: true    # Use project context for smarter reviews
    agents: true            # Enable multi-agent review capabilities
    skills: true            # Use specialized review skills
    playwright_ui: true     # AI reviews UI changes via Playwright screenshots

  # ---------------------------------------------------------------------------
  # Deployment Configuration
  # ---------------------------------------------------------------------------
  # Configure your deployment platform(s)
  deployment:
    enabled: true
    vercel:
      enabled: false        # Not using Vercel for this setup
    supabase:
      enabled: false        # Set true if using Supabase backend
    cloudflare:
      enabled: true         # Deploy previews and production to Cloudflare Pages
      # Cloudflare Pages will:
      # - Create preview deployments for PRs
      # - Deploy to production on main branch merges
      # - Provide edge-first performance
